#!/bin/bash

echo "========================================="
echo "  ARCHIVUS MANUAL TESTING CHECKLIST"
echo "========================================="
echo ""
echo "Frontend URL: http://localhost:3000"
echo "Backend URL: http://172.24.32.1:8080"
echo ""
echo "✅ VERIFIED: Backend is healthy"
echo "✅ VERIFIED: Frontend is running"
echo "✅ VERIFIED: Authentication tests pass"
echo "✅ VERIFIED: Document API tests pass"
echo ""
echo "----------------------------------------"
echo "  MANUAL UI TESTING STEPS"
echo "----------------------------------------"
echo ""
echo "1. LANDING PAGE (http://localhost:3000)"
echo "   ✓ Verify landing page loads"
echo "   ✓ Click 'Start Free Trial' button"
echo "   ✓ Should redirect to login page"
echo ""
echo "2. LOGIN PAGE (http://localhost:3000/auth/login)"
echo "   ✓ Page loads with email/password fields"
echo "   ✓ Google and GitHub OAuth buttons visible"
echo "   ✓ 'Sign up' link works"
echo ""
echo "3. REGISTER PAGE (http://localhost:3000/auth/register)"
echo "   ✓ Create a test account:"
echo "     Email: test@example.com"
echo "     Password: Test123!"
echo "     Company: Test Company"
echo ""
echo "4. DASHBOARD (http://localhost:3000/dashboard)"
echo "   ✓ Should redirect to login if not authenticated"
echo "   ✓ After login, dashboard should load"
echo "   ✓ Sidebar navigation visible"
echo ""
echo "5. DOCUMENT UPLOAD"
echo "   ✓ Click 'Upload Document' in sidebar"
echo "   ✓ Drag and drop a test file"
echo "   ✓ Verify upload progress"
echo ""
echo "6. DOCUMENT LIST (http://localhost:3000/dashboard/documents)"
echo "   ✓ Inbox-style list loads"
echo "   ✓ Documents show with metadata"
echo "   ✓ Hover states work"
echo "   ✓ Click document to open detail panel"
echo ""
echo "7. SEARCH FUNCTIONALITY"
echo "   ✓ Press Cmd+K (Mac) or Ctrl+K (Windows)"
echo "   ✓ Search modal opens"
echo "   ✓ Type a query and press Enter"
echo "   ✓ Results page shows with tabs"
echo ""
echo "8. RESPONSIVE DESIGN"
echo "   ✓ Resize browser to test breakpoints"
echo "   ✓ Mobile: Single column layout"
echo "   ✓ Tablet: Two column layout"
echo "   ✓ Desktop: Three column layout"
echo ""
echo "----------------------------------------"
echo "  KNOWN ISSUES TO CHECK"
echo "----------------------------------------"
echo ""
echo "1. API Integration:"
echo "   - Ensure NEXT_PUBLIC_API_URL is correct"
echo "   - Check for CORS errors in console"
echo "   - Verify JWT tokens in localStorage"
echo ""
echo "2. Search Features:"
echo "   - Search endpoint validation errors (expected)"
echo "   - All search types should work"
echo ""
echo "3. Document Management:"
echo "   - Some fields may show as undefined"
echo "   - Soft delete behavior"
echo ""
echo "========================================="
echo "  QUICK TEST COMMANDS"
echo "========================================="
echo ""
echo "# Create a test user via API:"
echo "curl -X POST http://172.24.32.1:8080/api/v1/auth/tenant \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"company_name\":\"UI Test Co\",\"admin_email\":\"uitest@example.com\",\"admin_password\":\"Test123!\",\"admin_first_name\":\"UI\",\"admin_last_name\":\"Test\"}'"
echo ""
echo "# Check frontend build:"
echo "npm run build"
echo ""
echo "# Run linting:"
echo "npm run lint"
echo ""